### ISSUE TITLE
Problems to build it on iOS with simple_permissions library

### ISSUE THREAD

**Issue by jr00n** [Datlyfe/flutter-tunein#2]
First of all I had to add
target 'Runner' do
  use_frameworks!
in Podfile 
and a version in pubspec.

now I've got a white screen and this message

Running Xcode build...
Xcode build done.                                           10,2s
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermission on channel simple_permissions)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      SimplePermissions.requestPermission (package:simple_permissions/simple_permissions.dart:24:35)
<asynchronous suspension>
#2      main (package:Tunein/main.dart:16:27)
<asynchronous suspension>
#3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1500:12)
#8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:17<…>
Syncing files to device iPhone X...

**Comment by Datlyfe** [comment]
Hey, thanks for opening an issue and sorry for the late response.
i haven't tested the app on an ios device or in Xcode for that matter, i was mainly focused on developing for android if you can inspect the problem and open a PR that would be very appreciated.

**Comment by perseval** [comment]
this link can resolve your problem : https://stackoverflow.com/a/60426942/8385251
